### ISSUE TITLE
Add support for vimwiki (with markdown syntax) filetype?

### ISSUE THREAD

**Issue by yaohunzhanyue** [gera2ld/coc-markmap#4]
pls...

**Comment by gera2ld** [comment]
It's possible if you can provide a syntax parser for vimwiki. AFAICT the syntax of vimwiki is quite different from that of Markdown.

**Comment by yaohunzhanyue** [comment]
@gera2ld Vimwiki support markdown syntax, but filetype is vimwiki.

**Comment by gera2ld** [comment]
I don't want to enable this in vimwiki by default because vimwiki syntax is not always supported.

However you can forcibly enable it as a workaround if you are sure the syntax in your file is valid Markdown. Here is what to do:

Add this to your vimrc:

```viml
nmap <Leader>m :call CocAction('activeExtension', 'coc-markmap') \| CocCommand markmap.create<CR>
```

Then `<Leader>m` will work in any files. Of course you can change the key mapping.

If you want it to work only for vimwiki, try this:

```viml
autocmd FileType vimwiki nmap <buffer> <Leader>m :call CocAction('activeExtension', 'coc-markmap') \| CocCommand markmap.create<CR>
```
